apiVersion : apps/v1
kind: Deployment
metadata:
  name: sampleapp 
spec:
  replicas: {{replicaNo}}
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp 
    spec:
      containers:
        - name: sampleapp 
          image: testacrxx1.azurecr.io/sampleapp
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: k8sexampleacrauth
        
